---
abstract: 'Rinci access protocol'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Riap
requires:
  Rinci: v1.1.19
resources:
  homepage: http://metacpan.org/release/Riap
  repository: http://github.com/sharyanto/perl-Riap
version: 1.1.16
